id: 'ttgf0p2'
name: 'Tiny Tapeout GF 0.2'
pdk: 'gf180mcuD'
end_date: '2025-11-24'
project_dir: 'projects'
top_level_macro: 'tt_gf_wrapper'
powered_netlists: true
no_power_gating: true

datasheet_config:
  theme_override_colour: tt.colours.THEME_SKY_BLUE
  link_override_colour: tt.colours.THEME_SKY_BLUE

  artwork:
    - {id: TT_POCA_01_A, rotate: -90deg}
    - {id: TT_POCA_01_B, rotate: -90deg}
    - {id: TT_POCA_01_C, rotate: -90deg}
    - {id: TT_POCA_01_D, rotate: -90deg}
    - {id: TT_POCA_01_E, rotate: -90deg}
    - {id: TT_POCA_01_F, rotate: 90deg}
    - {id: TT_POCA_01_G, rotate: 90deg}
    - {id: TT_POCA_01_H, rotate: -90deg}
    - {id: TT_POCA_01_I, rotate: 90deg}

  include:
    - docs/chip_map.typ
    - docs/funding.typ