name: gds

on:
  workflow_dispatch:
  push:
    # Don't run on project submissions:
    branches-ignore:
      - projects/tt_um_*
  pull_request:
    # Don't run on project submissions:
    paths-ignore:
      - projects/tt_um_*/**

jobs:
  gds:
    env:
      PYTHONIOENCODING: utf-8
      PDK: gf180mcuD
      PDK_ROOT: ${{ github.workspace }}/gf180mcu
      TT_CONFIG: gf180mcuD.yaml:../../mux_overrides.yaml
      # Uncomment the following line to build only the specified projects:
      #TT_ONLY_PROJECTS: tt_um_chip_rom,tt_um_factory_test

    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false
          docker-images: false
          swap-storage: false
          android: false

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r tt-multiplexer/py/requirements.txt -r tt/requirements.txt -r verilog/dv/mux/requirements.txt

      - name: Update caravel configuration
        run: python ./tt/configure.py --update-shuttle

      - name: Install Nix and configure FOSSi cache
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-substituters = https://nix-cache.fossi-foundation.org
            extra-trusted-public-keys = nix-cache.fossi-foundation.org:3+K59iFwXqKsL7BNu6Guy0v+uTlwsxYQxjspXzqLYQs=

      - name: Download wafer.space macros
        if: ${{env.PDK}} == 'gf180mcuD'
        run: |
          wget -O tt-multiplexer/ol2/tt_top/gds/gf180mcu_ws_ip__id.gds https://raw.githubusercontent.com/wafer-space/gf180mcu-project-template/refs/tags/1.2.3/ip/gf180mcu_ws_ip__id/gds/gf180mcu_ws_ip__id.gds
          wget -O tt-multiplexer/ol2/tt_top/lef/gf180mcu_ws_ip__id.lef https://raw.githubusercontent.com/wafer-space/gf180mcu-project-template/refs/tags/1.2.3/ip/gf180mcu_ws_ip__id/lef/gf180mcu_ws_ip__id.lef
          wget -O tt-multiplexer/ol2/tt_top/gds/gf180mcu_ws_ip__logo.gds https://raw.githubusercontent.com/wafer-space/gf180mcu-project-template/refs/tags/1.2.3/ip/gf180mcu_ws_ip__logo/gds/gf180mcu_ws_ip__logo.gds
          wget -O tt-multiplexer/ol2/tt_top/lef/gf180mcu_ws_ip__logo.lef https://raw.githubusercontent.com/wafer-space/gf180mcu-project-template/refs/tags/1.2.3/ip/gf180mcu_ws_ip__logo/lef/gf180mcu_ws_ip__logo.lef

      # Use LibreLane to build the macros and the final GDS
      - name: Harden Chip ROM
        run: nix-shell $GITHUB_WORKSPACE/librelane/shell.nix --run "python -m librelane tt/rom/config.json"

      - name: Harden tt_ctrl
        working-directory: tt-multiplexer/ol2/tt_ctrl
        run: nix-shell $GITHUB_WORKSPACE/librelane/shell.nix --run "python build.py"

      - name: Harden tt_mux
        working-directory: tt-multiplexer/ol2/tt_mux
        run: nix-shell $GITHUB_WORKSPACE/librelane/shell.nix --run "python build.py"

      - name: Copy macros
        run: python ./tt/configure.py --copy-macros

      - name: Generate corner logos
        run: python ./tt/tech/gf180mcuD/logo/generate_logos.py --output-dir tt-multiplexer/ol2/tt_top

      - name: Harden tt_top
        working-directory: tt-multiplexer/ol2/tt_top
        run: nix-shell $GITHUB_WORKSPACE/librelane/shell.nix --run "python build.py"

      - name: Create empty spef file if missing (temporary workaround)
        run: |
          LATEST_RUN=$(find tt-multiplexer/ol2/tt_top/runs -name 'RUN_*' | sort | tail -n 1)
          if [ ! -d "$LATEST_RUN/final/spef" ]; then mkdir -p "$LATEST_RUN/final/spef"; fi

      - name: Copy final results
        run: python ./tt/configure.py --copy-final-results

      - name: Create foundry submission directory
        run: python ./tt/configure.py --create-foundry-submission

      - name: Print build summary
        run: |
          OAS_FILE=foundry_submission/oas/*.oas
          OAS_SIZE=$(stat --printf='%s' $OAS_FILE | numfmt --to=iec --suffix=B)
          SHA1_SUM=$(sha1sum $OAS_FILE | cut -d' ' -f1)
          cat <<EOF | tee -a $GITHUB_STEP_SUMMARY
          ## Build Summary
          - **Commit:** ${{ github.event.head_commit.id }}
          - **OAS file:** $(basename $OAS_FILE)
          - **Size:** $OAS_SIZE
          - **SHA1:** \`$SHA1_SUM\`
          EOF

      - name: upload GDS artifact
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: GDS
          path: tt-multiplexer/ol2/tt_top/runs/RUN_*/*

      - name: upload macros artifact
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: macros
          path: |
            tt-multiplexer/cfg/*.yaml
            tt-multiplexer/ol2/tt_top/gds/*
            tt-multiplexer/ol2/tt_top/lef/*
            tt-multiplexer/ol2/tt_top/spef/*
            tt-multiplexer/ol2/tt_top/verilog/*
            tt-multiplexer/ol2/tt_mux/runs/RUN_*/*
            tt-multiplexer/ol2/tt_ctrl/runs/RUN_*/*

      - name: upload shuttle_index.json
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: shuttle_index
          path: shuttle_index.json

      - name: upload foundry submission directory
        uses: actions/upload-artifact@v4
        with:
          name: foundry_submission
          path: foundry_submission

      # Install iverilog (required for GL simulation)
      - name: install iverilog
        run: sudo apt-get update && sudo apt-get install -y iverilog

      - name: GL simulation
        working-directory: verilog/dv/mux
        env:
          EXPECTED_REPO: ${{ github.repository }}
        run: |
          # temporary workaround for missing bits in pad_raw:
          sed -i 's/inout \[69:0\] pad_raw/inout [73:0] pad_raw/' ../../../foundry_submission/verilog/gl/tt_gf_wrapper.v

          make clean test_mux_gl WAVES=yes
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      - name: upload GL test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: gl_test_vcd
          path: |
            verilog/dv/mux/results.xml
            verilog/dv/mux/test_mux.vcd
            verilog/dv/mux/test_mux.gtkw
