name: verification

on:
  workflow_dispatch:
  push:
    # Don't run on project submissions:
    branches-ignore:
      - projects/tt_um_*
  pull_request:
    # Don't run on project submissions:
    paths-ignore:
      - projects/tt_um_*/**

jobs:
  verification:
    env:
      PDK: gf180mcuD
      PDK_ROOT: ${{ github.workspace }}/gf180mcu
      TT_CONFIG: gf180mcuD.yaml

    # ubuntu
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Set Python up
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r tt/requirements.txt -r tt-multiplexer/py/requirements.txt -r verilog/dv/mux/requirements.txt

      - name: install iverilog
        run: sudo apt-get update && sudo apt-get install -y iverilog

      - name: Configure the multiplexer for testing
        run: python ./tt/configure.py --update-shuttle --test

      # run first set of tests
      - name: Mux simulation
        working-directory: verilog/dv/mux
        env:
          EXPECTED_REPO: ${{ github.repository }}
        run: |
          make clean test_mux
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml
